import "./globals.css";
import { NextUIProvider } from '@nextui-org/react';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import { Toaster } from "react-hot-toast";
import { Inter } from 'next/font/google';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        <Toaster position="bottom-center" />
          <NextUIProvider session={session}>
            <Header />
            {children}
            <Footer />
          </NextUIProvider>
      </body>
    </html>
  );
}